server:
  port: 8082

kafka:
  topic: 'topic.test'
  group-id: 'group_id'
  concurrency: 3
  poll-timeout: 3000
  server-config: 'localhost:9092'
  dlt:
    topic: 'topic.test.DLT'
  retry:
    initial-interval: 1000
    multiplier: 3
    max-interval: 10000
    max-retries: 3